//
//  Ids.h
//  dream
//
//  Created by Yermek Garifullanov on 10/7/13.
//  Copyright (c) 2013 mekchi. All rights reserved.
//

#ifndef dream_Ids_h
#define dream_Ids_h

// --- GAMEOBJECT ---

enum E_GAMEOBJECT_ID
{
    GOI_PROTAGONIST = 0,
    GOI_ENVIRONMENT,
    GOI_LEVEL,
    GOI_BOX_COLOR,
    GOI_BOX_SOUND,
    GOI_BOX_WORD,
    NUM_GAMEOBJECT_ID
};

enum E_PROTAGONIST_STATUS
{
    PRTGS_IDLE = 0,
    PRTGS_MOVE,
    PRTGS_TOUCH
};

enum E_ENVIRONMENT_STATUS
{
    ENVS_IDLE = 0,
    ENVS_CAMERA_MOVE,
    ENVS_WAVE_DONE
};

// --- GAMEOBJECT ---

// --- COMPONENT ---

enum E_FAMILY_COMPONENT_ID
{
    FCI_PROTAGONIST = 0,
    FCI_ENVIRONMENT,
    FCI_LEVEL,
    FCI_MIRACLE_BOX
};

// order is important

enum E_COMPONENT_ID
{
    CI_ENVIRONMENT_HEIGHTFIELD = 0,
    CI_PROTAGONIST_SPHERE,
    CI_RANDOM_LEVEL,
    CI_MIRACLE_BOX_00,
    CI_MIRACLE_BOX_01,
    NUM_COMPONENT_ID
};

// --- COMPONENT ---

// --- MESSAGE IDS ---

enum E_MESSAGE_RESULT
{
    MR_SUCCESS = 0,
    MR_FAILD,
    MR_ERROR,
    MR_IGNORE
};

enum E_MESSAGE_TYPE
{
    MT_UPDATE = 0,
    MT_RENDER,
    MT_UPDATE_RENDER,
    MT_PROTAGONIST_COMPUTE_FORCE,
    MT_PROTAGONIST_POSITION,
    MT_PROTAGONIST_CHANGE_POSITION,
    MT_UPDATE_PROJECTION,
    MT_MOVE,
    MT_TOUCHED_OBJECT,
    MT_TOUCHED_START,
    MT_TOUCHED_MOVE,
    MT_TOUCHED_STOP,
    MT_SPACE,
    MT_PROTAGONIST_TOUCH,
    MT_ENVIRONMENT_TOUCH,
    MT_PROTAGONIST_STATUS,
    MT_ENVIRONMENT_STATUS,
    NUM_MESSAGE_TYPE
};

// --- MESSAGE IDS ---

#endif
